"""
Comprehensive Mining Industry Asset Seed Data
For PT. ANDA SELALU UNTUNG (Mining & Processing Operations)

Asset Categories:
1. Physical/Fixed Assets (Mining Equipment, Processing Facilities, Infrastructure)
2. Fleet & Vehicles
3. Land and Concessions
4. Digital & Document Assets
5. IT and Digital Infrastructure
6. Inventory & Consumables
7. Human Resource Assets (Certifications & Training)
8. Financial Assets (Depreciation, Maintenance History)
9. Environmental & Sustainability Assets
"""

from datetime import datetime, timedelta
from typing import Dict, List

# ============================================================================
# 1. MINING EQUIPMENT & PROCESSING FACILITIES
# ============================================================================

MINING_EQUIPMENT = [
    {
        "id": "EQP-001",
        "name": "Excavator CAT 390F",
        "category": "Mining Equipment",
        "subcategory": "Excavators",
        "location": "Block Alpha - Pit 1",
        "manufacturer": "Caterpillar",
        "model": "CAT 390F",
        "serial_number": "CAT390F-2021-001",
        "asset_status": "operational",
        "acquisition_date": "2021-03-15",
        "purchase_price": 1500000.00,
        "current_value": 1050000.00,
        "warranty_expiry": "2024-03-15",
        "status_indicator": "🟢 Good",
        "last_maintenance": "2026-03-10",
        "next_maintenance": "2026-04-10",
        "maintenance_interval": "30 days",
        "hourly_rate": 950.00,
        "operational_hours": 8500,
        "fuel_type": "Diesel",
        "capacity": "6.4m³",
        "specifications": {
            "engine_power": "462 kW",
            "weight": "78000 kg",
            "bucket_size": "2.7-3.2 m³"
        },
        "documents": ["warranty_doc_001", "manual_exc_001", "inspection_report_2024"],
        "linked_maintenance_records": 8,
        "carbon_footprint_kg_co2": 850000,
    },
    {
        "id": "EQP-002",
        "name": "Dozerbull Komatsu D455AX",
        "category": "Mining Equipment",
        "subcategory": "Bulldozers",
        "location": "Block Beta - Reclamation Area",
        "manufacturer": "Komatsu",
        "model": "D455AX",
        "serial_number": "KOM-D455AX-2020-022",
        "asset_status": "operational",
        "acquisition_date": "2020-06-20",
        "purchase_price": 1200000.00,
        "current_value": 840000.00,
        "warranty_expiry": "2023-06-20",
        "status_indicator": "🟢 Good",
        "last_maintenance": "2026-03-15",
        "next_maintenance": "2026-04-15",
        "maintenance_interval": "30 days",
        "operational_hours": 12400,
        "blade_width": "3.7m",
        "specifications": {
            "engine_power": "373 kW",
            "weight": "54800 kg",
            "blade_capacity": "12.5m³"
        },
        "linked_maintenance_records": 12,
        "carbon_footprint_kg_co2": 920000,
    },
    {
        "id": "EQP-003",
        "name": "Dump Truck Volvo FMX 6x4",
        "category": "Mining Equipment",
        "subcategory": "Dump Trucks",
        "location": "Block Gamma - Transport Route",
        "manufacturer": "Volvo",
        "model": "FMX 6x4",
        "serial_number": "VLV-FMX-2022-015",
        "asset_status": "operational",
        "acquisition_date": "2022-01-10",
        "purchase_price": 450000.00,
        "current_value": 337500.00,
        "warranty_expiry": "2025-01-10",
        "status_indicator": "🟢 Good",
        "last_maintenance": "2026-03-20",
        "next_maintenance": "2026-04-20",
        "maintenance_interval": "30 days",
        "payload_capacity": "42 tonne",
        "specifications": {
            "engine_power": "480 hp",
            "transmission": "I-Shift automatic",
            "bed_size": "6.5m x 2.6m x 1.0m"
        },
        "linked_maintenance_records": 6,
        "carbon_footprint_kg_co2": 450000,
    },
    {
        "id": "EQP-004",
        "name": "Dredger KIP-3000 (Offshore)",
        "category": "Mining Equipment",
        "subcategory": "Dredgers",
        "location": "Offshore Block Delta - Depth 25m",
        "manufacturer": "Royal IHC",
        "model": "KIP-3000",
        "serial_number": "RIV-KIP-3000-2019",
        "asset_status": "operational",
        "acquisition_date": "2019-05-01",
        "purchase_price": 8500000.00,
        "current_value": 5950000.00,
        "warranty_expiry": "2024-05-01",
        "status_indicator": "🟡 Maintenance Required",
        "last_maintenance": "2026-02-28",
        "next_maintenance": "2026-04-28",
        "maintenance_interval": "60 days",
        "dredging_capacity": "3000 t/h",
        "specifications": {
            "pump_power": "2500 kW",
            "ladder": "40m",
            "vessel_length": "90m"
        },
        "linked_maintenance_records": 18,
        "carbon_footprint_kg_co2": 2800000,
    },
    {
        "id": "EQP-005",
        "name": "Drill Rig Atlas Copco D9-13",
        "category": "Mining Equipment",
        "subcategory": "Drills",
        "location": "Block Alpha - Exploration Area",
        "manufacturer": "Atlas Copco",
        "model": "D9-13",
        "serial_number": "ACO-D9-13-2021",
        "asset_status": "operational",
        "acquisition_date": "2021-07-10",
        "purchase_price": 650000.00,
        "current_value": 455000.00,
        "warranty_expiry": "2024-07-10",
        "status_indicator": "🟢 Good",
        "last_maintenance": "2026-03-18",
        "next_maintenance": "2026-04-18",
        "maintenance_interval": "30 days",
        "drilling_depth": "300m",
        "specifications": {
            "compressor_power": "450 kW",
            "hole_diameter": "25-115 mm",
            "fuel_consumption": "45 L/h"
        },
        "linked_maintenance_records": 7,
        "carbon_footprint_kg_co2": 380000,
    },
    {
        "id": "FAC-001",
        "name": "Tin Smelter Plant - Main Unit",
        "category": "Processing Facilities",
        "subcategory": "Smelters and Refineries",
        "location": "Processing Plant - Block Omega",
        "manufacturer": "Ausmelt Ltd",
        "equipment_type": "Reverberatory Furnace",
        "capacity": "250 tpd",
        "asset_status": "operational",
        "acquisition_date": "2016-11-20",
        "purchase_price": 12000000.00,
        "current_value": 7200000.00,
        "warranty_expiry": "2019-11-20",
        "status_indicator": "🟡 Scheduled Maintenance",
        "last_maintenance": "2026-01-15",
        "next_maintenance": "2026-06-15",
        "maintenance_interval": "180 days",
        "operating_efficiency": "94.5%",
        "specifications": {
            "furnace_temperature": "1350°C",
            "energy_consumption": "680 kWh/ton",
            "stack_capacity": "500 m³"
        },
        "linked_maintenance_records": 22,
        "carbon_footprint_kg_co2": 4200000,
    },
    {
        "id": "FAC-002",
        "name": "Concentration Plant - Flotation Circuit",
        "category": "Processing Facilities",
        "subcategory": "Concentration plants",
        "location": "Processing Plant - Block Omega",
        "manufacturer": "Metso Outotec",
        "equipment_type": "Rougher Flotation Cells",
        "capacity": "500 tpd",
        "asset_status": "operational",
        "acquisition_date": "2018-03-10",
        "purchase_price": 3500000.00,
        "current_value": 2275000.00,
        "warranty_expiry": "2023-03-10",
        "status_indicator": "🟢 Good",
        "last_maintenance": "2026-02-20",
        "next_maintenance": "2026-04-20",
        "maintenance_interval": "60 days",
        "recovery_rate": "97.2%",
        "specifications": {
            "cell_volume": "5x300 m³",
            "air_flow": "12000 m³/h",
            "power_requirement": "850 kWh/h"
        },
        "linked_maintenance_records": 14,
        "carbon_footprint_kg_co2": 1500000,
    },
    {
        "id": "FAC-003",
        "name": "Slurry Storage Tank Complex",
        "category": "Processing Facilities",
        "subcategory": "Storage tanks",
        "location": "Processing Plant - Storage Area",
        "manufacturer": "Tank Industries",
        "equipment_type": "Concrete Lined Storage Tanks",
        "capacity": "50000 m³",
        "asset_status": "operational",
        "acquisition_date": "2015-08-05",
        "purchase_price": 2800000.00,
        "current_value": 1568000.00,
        "warranty_expiry": "2020-08-05",
        "status_indicator": "🟡 Inspection Due",
        "last_maintenance": "2025-12-10",
        "next_maintenance": "2026-06-10",
        "maintenance_interval": "180 days",
        "current_content": "Tin slurry concentrate",
        "specifications": {
            "total_capacity": "50000 m³",
            "tank_count": 4,
            "liner_material": "HDPE 2mm",
            "leakage_rate": "0.001%/month"
        },
        "linked_maintenance_records": 8,
        "carbon_footprint_kg_co2": 150000,
    },
    {
        "id": "INF-001",
        "name": "Main Warehouse Building",
        "category": "Infrastructure",
        "subcategory": "Warehouses",
        "location": "Industrial Zone - Block A",
        "construction_type": "Steel frame with concrete floor",
        "area_sqm": 5000,
        "asset_status": "operational",
        "acquisition_date": "2014-02-15",
        "purchase_price": 1200000.00,
        "current_value": 840000.00,
        "warranty_expiry": "N/A",
        "status_indicator": "🟢 Good",
        "last_maintenance": "2026-01-20",
        "next_maintenance": "2026-07-20",
        "maintenance_interval": "180 days",
        "stored_items_count": 487,
        "storage_capacity_percent": "78%",
        "specifications": {
            "roof_type": "Metal deck",
            "flooring": "Reinforced concrete",
            "ventilation": "12 units",
            "fire_rating": "2-hour rated"
        },
        "linked_maintenance_records": 6,
    },
    {
        "id": "INF-002",
        "name": "Maintenance Workshop & Plant",
        "category": "Infrastructure",
        "subcategory": "Workshop facilities",
        "location": "Industrial Zone - Block B",
        "construction_type": "Multi-bay structure",
        "area_sqm": 2500,
        "asset_status": "operational",
        "acquisition_date": "2012-09-10",
        "purchase_price": 800000.00,
        "current_value": 480000.00,
        "warranty_expiry": "N/A",
        "status_indicator": "🟡 Roof Maintenance Needed",
        "last_maintenance": "2025-11-15",
        "next_maintenance": "2026-05-15",
        "maintenance_interval": "180 days",
        "equipment_stations": 12,
        "technician_capacity": 25,
        "specifications": {
            "bays": 6,
            "lift_capacity": "50 tonnes each",
            "power_supply": "1000 kW",
            "compressed_air": "150 cfm"
        },
        "linked_maintenance_records": 11,
    },
    {
        "id": "INF-003",
        "name": "Power Generation Station (Diesel 5MW)",
        "category": "Infrastructure",
        "subcategory": "Power supply stations",
        "location": "Utility Block - Power Zone",
        "manufacturer": "Cummins",
        "equipment_type": "Diesel Generator Set",
        "capacity_mw": 5.0,
        "asset_status": "operational",
        "acquisition_date": "2017-04-20",
        "purchase_price": 850000.00,
        "current_value": 595000.00,
        "warranty_expiry": "2022-04-20",
        "status_indicator": "🟢 Good",
        "last_maintenance": "2026-03-01",
        "next_maintenance": "2026-04-01",
        "maintenance_interval": "30 days",
        "fuel_consumption_lph": 1050,
        "efficiency_percent": "42.5%",
        "specifications": {
            "engine": "Cummins KTA50 V16",
            "output_frequency": "50 Hz",
            "voltage": "10.5 kV",
            "auto_start": "Yes"
        },
        "linked_maintenance_records": 15,
        "carbon_footprint_kg_co2": 2500000,
    },
    {
        "id": "INF-004",
        "name": "Port & Jetty Infrastructure (Ore Loading)",
        "category": "Infrastructure",
        "subcategory": "Port/Jetty facilities",
        "location": "Offshore - Distance 5km from coast",
        "construction_type": "Steel Pile Jetty",
        "structure_length_m": 450,
        "asset_status": "operational",
        "acquisition_date": "2010-06-01",
        "purchase_price": 5500000.00,
        "current_value": 2750000.00,
        "warranty_expiry": "N/A",
        "status_indicator": "🟡 Structural Inspection Due",
        "last_maintenance": "2025-09-20",
        "next_maintenance": "2026-09-20",
        "maintenance_interval": "365 days",
        "annual_throughput_tonnes": 500000,
        "loading_equipment_count": 3,
        "specifications": {
            "berthing_capacity": "2 vessels 20,000 DWT",
            "water_depth": "12-15m",
            "pile_material": "Steel H-section",
            "fender_type": "Rubber",
            "pile_corrosion_prevention": "Cathodic protection"
        },
        "linked_maintenance_records": 9,
    },
]

# ============================================================================
# 2. FLEET & VEHICLES
# ============================================================================

FLEET_VEHICLES = [
    {
        "id": "VEH-001",
        "name": "Haul Truck HT-001",
        "vehicle_type": "Haul Truck",
        "manufacturer": "Volvo",
        "model": "FMX 6x4",
        "year": 2022,
        "registration": "MN-7743-AB",
        "location": "Block Alpha - Primary Route",
        "asset_status": "operational",
        "purchase_price": 450000.00,
        "current_value": 337500.00,
        "acquisition_date": "2022-01-10",
        "fuel_type": "Diesel",
        "fuel_capacity_liters": 350,
        "current_fuel_liters": 280,
        "fuel_consumption_lpl": 0.22,
        "payload_capacity_tonnes": 42,
        "status_indicator": "🟢 Good",
        "last_service": "2026-03-15",
        "next_service": "2026-04-15",
        "service_interval_days": 30,
        "odometer_km": 125400,
        "engine_hours": 8540,
        "tire_condition": "85% tread remaining",
        "maintenance_cost_ytd": 8500,
        "operating_efficiency": "94%",
        "specifications": {
            "engine_power": "480 hp",
            "transmission": "I-Shift 12-speed automatic",
            "brakes": "Air disc",
            "suspension": "Air suspension"
        },
        "assigned_driver": "Ahmad Wijaya",
        "last_trip": "2026-03-21 14:30",
        "trips_this_month": 24,
        "total_payload_tonnes_ytd": 925,
        "carbon_emissions_kg_co2": 2850,
    },
    {
        "id": "VEH-002",
        "name": "Loader LDR-002",
        "vehicle_type": "Wheel Loader",
        "manufacturer": "Komatsu",
        "model": "WA480-8",
        "year": 2020,
        "registration": "MN-5521-CD",
        "location": "Block Gamma - Loading Area",
        "asset_status": "operational",
        "purchase_price": 380000.00,
        "current_value": 266000.00,
        "acquisition_date": "2020-05-15",
        "fuel_type": "Diesel",
        "fuel_capacity_liters": 330,
        "current_fuel_liters": 165,
        "fuel_consumption_lpl": 0.45,
        "payload_capacity_tonnes": 32,
        "status_indicator": "🟢 Good",
        "last_service": "2026-03-10",
        "next_service": "2026-04-10",
        "service_interval_days": 30,
        "operating_hours": 14250,
        "bucket_capacity_m3": 3.2,
        "maintenance_cost_ytd": 12300,
        "operating_efficiency": "91%",
        "specifications": {
            "engine_power": "354 kW",
            "transmission": "Torque converter",
            "hydraulic_pump": "270 L/min",
            "max_lift_height": "3.3m"
        },
        "assigned_operator": "Budi Santoso",
        "tons_loaded_this_month": 580,
        "carbon_emissions_kg_co2": 4200,
    },
    {
        "id": "VEH-003",
        "name": "Utility Vehicle - Admin Transport",
        "vehicle_type": "Pickup Truck",
        "manufacturer": "Toyota",
        "model": "Hilux 4x4 Double Cab",
        "year": 2023,
        "registration": "MN-1234-EF",
        "location": "Base Camp - Office Area",
        "asset_status": "operational",
        "purchase_price": 45000.00,
        "current_value": 36000.00,
        "acquisition_date": "2023-06-01",
        "fuel_type": "Diesel",
        "fuel_capacity_liters": 80,
        "current_fuel_liters": 50,
        "fuel_consumption_lpl": 0.08,
        "payload_capacity_tonnes": 1.5,
        "status_indicator": "🟢 Good",
        "last_service": "2026-03-18",
        "next_service": "2026-04-18",
        "service_interval_days": 30,
        "odometer_km": 28500,
        "maintenance_cost_ytd": 600,
        "passengers": 6,
        "specifications": {
            "engine": "2.8L Turbo Diesel",
            "transmission": "6-speed automatic",
            "bed_size": "5.0m x 1.5m",
            "gvwr": "2520 kg"
        },
        "assigned_driver": "Management Staff",
        "monthly_distance_km": 2400,
        "carbon_emissions_kg_co2": 285,
    },
    {
        "id": "VEH-004",
        "name": "Supply Vessel - MV Integritas",
        "vehicle_type": "Supply Boat",
        "manufacturer": "Korean Shipbuilder",
        "model": "OSV 3000 DP",
        "year": 2018,
        "registration": "ID-2018-OSV-001",
        "location": "Offshore Supply Base - Block Delta",
        "asset_status": "operational",
        "purchase_price": 2800000.00,
        "current_value": 1960000.00,
        "acquisition_date": "2018-03-15",
        "fuel_type": "Marine Diesel Oil (MDO)",
        "fuel_capacity_tonnes": 350,
        "current_fuel_tonnes": 250,
        "fuel_consumption_tph": 8.5,
        "payload_capacity_tonnes": 400,
        "status_indicator": "🟢 Good",
        "last_service": "2026-02-28",
        "next_service": "2026-05-28",
        "service_interval_days": 90,
        "vessel_length_m": 76,
        "vessel_beam_m": 17,
        "draft_m": 5.2,
        "gross_tonnage": 3000,
        "maintenance_cost_ytd": 95000,
        "dynamic_positioning": "Yes (DP2)",
        "crew_capacity": 25,
        "specifications": {
            "main_engines": "2x Rolls Royce 2500 kW",
            "azimuth_thrusters": "2x 1750 kW",
            "cargo_deck_area_m2": 1200,
            "crane_capacity_tonnes": 10
        },
        "assigned_captain": "Capt. Soekarno M",
        "annual_days_operational": 280,
        "total_distance_nm_ytd": 45000,
        "carbon_emissions_tonnes_co2": 380,
    },
    {
        "id": "VEH-005",
        "name": "Barge - TIN-BARGE-01",
        "vehicle_type": "Bulk Cargo Barge",
        "manufacturer": "Tanjung Perak Shipyard",
        "model": "OBM 4500 DWT",
        "year": 2015,
        "registration": "ID-2015-BARGE-07",
        "location": "Offshore Anchorage",
        "asset_status": "operational",
        "purchase_price": 1200000.00,
        "current_value": 600000.00,
        "acquisition_date": "2015-11-20",
        "fuel_type": "Marine Diesel Oil (MDO)",
        "fuel_capacity_tonnes": "N/A - towed",
        "payload_capacity_tonnes": 4500,
        "status_indicator": "🟢 Good",
        "last_service": "2026-01-15",
        "next_service": "2026-07-15",
        "service_interval_days": 180,
        "barge_length_m": 108,
        "barge_beam_m": 19,
        "draft_m": 4.5,
        "cargo_hold_volume_m3": 6800,
        "maintenance_cost_ytd": 28000,
        "tow_vessel": "MV Integritas",
        "specifications": {
            "hatch_covers": "Pontoon type",
            "hold_coating": "Epoxy resin",
            "cargo_compatibility": "Tin, minerals, general cargo",
            "crane_points": "8x50 tonne"
        },
        "operational_routes": ["Base → Offshore Blocks", "Processing Plant → Port"],
        "cargo_trips_ytd": 42,
        "total_cargo_shipped_tonnes": 189000,
    },
]

# ============================================================================
# 3. LAND & MINING CONCESSIONS
# ============================================================================

MINING_CONCESSIONS = [
    {
        "id": "CONC-001",
        "concession_name": "Mining Block Alpha",
        "iup_number": "IUP/OP/2018-001",
        "licensee": "PT. ANDA SELALU UNTUNG",
        "concession_area_hectares": 2500,
        "coordinates": {
            "lat_center": -6.2088,
            "lon_center": 106.8456,
            "bbox": {
                "north": -6.1850,
                "south": -6.2325,
                "east": 106.8750,
                "west": 106.8162
            }
        },
        "legal_status": "active",
        "expiry_date": "2028-12-31",
        "days_remaining": 650,
        "concession_type": "Tin Mining",
        "mineral_commodities": ["Tin (Sn)", "Heavy Minerals"],
        "mining_method": "Open Pit & Dredging",
        "current_phase": "Production",
        "zone_breakdown": {
            "mining_zone": {"area_ha": 1200, "status": "active"},
            "processing_zone": {"area_ha": 150, "status": "operational"},
            "tailings_zone": {"area_ha": 600, "status": "active"},
            "reclamation_zone": {"area_ha": 400, "status": "in-progress"},
            "buffer_zone": {"area_ha": 150, "status": "protected"}
        },
        "production_quota_tpa": 12000,
        "ytd_production_tonnes": 9500,
        "production_status": "on-track",
        "compliance_status": {
            "environmental": {"status": "compliant", "last_audit": "2026-02-15", "next_audit": "2026-08-15"},
            "social": {"status": "compliant", "last_audit": "2026-01-20", "next_audit": "2026-07-20"},
            "safety": {"status": "minor-issues", "last_audit": "2026-03-01", "next_audit": "2026-09-01"}
        },
        "equipment_deployed": ["EQP-001", "EQP-002", "VEH-001", "VEH-002"],
        "asset_count": 18,
        "workforce": 185,
        "linked_documents": ["IUP_cert_001", "survey_map_001", "env_plan_001"],
        "documents": {
            "iup_certificate": "IUP_cert_001",
            "survey_maps": ["survey_map_001", "survey_map_002"],
            "environmental_plan": "env_plan_001",
            "social_plan": "social_plan_001"
        },
    },
    {
        "id": "CONC-002",
        "concession_name": "Mining Block Beta",
        "iup_number": "IUP/OP/2019-002",
        "licensee": "PT. ANDA SELALU UNTUNG",
        "concession_area_hectares": 3500,
        "coordinates": {
            "lat_center": -6.3200,
            "lon_center": 106.9100,
            "bbox": {
                "north": -6.2900,
                "south": -6.3500,
                "east": 106.9450,
                "west": 106.8750
            }
        },
        "legal_status": "active",
        "expiry_date": "2029-06-30",
        "days_remaining": 805,
        "concession_type": "Tin Mining (Offshore-Adjacent)",
        "mineral_commodities": ["Tin (Sn)", "Tungsten (W)"],
        "mining_method": "Dredging + Land-based",
        "current_phase": "Production Ramp-Up",
        "production_quota_tpa": 18000,
        "ytd_production_tonnes": 8200,
        "production_status": "below-budget",
        "equipment_deployed": ["EQP-004", "EQP-005"],
        "asset_count": 22,
        "workforce": 220,
    },
    {
        "id": "CONC-003",
        "concession_name": "Exploration Block Gamma",
        "iup_number": "IUP/EX/2020-003",
        "licensee": "PT. ANDA SELALU UNTUNG",
        "concession_area_hectares": 2500,
        "coordinates": {
            "lat_center": -6.1500,
            "lon_center": 107.0500,
        },
        "legal_status": "pending-renewal",
        "expiry_date": "2027-03-31",
        "days_remaining": 384,
        "concession_type": "Exploration License",
        "mineral_commodities": ["Rare Earth", "Gold", "Copper"],
        "mining_method": "Exploratory Drilling",
        "current_phase": "Exploration & Resource Assessment",
        "drilling_locations": 18,
        "ytd_drilling_meters": 3450,
        "equipment_deployed": ["EQP-005"],
        "asset_count": 12,
        "workforce": 45,
    },
]

# ============================================================================
# 4. DIGITAL & DOCUMENT ASSETS
# ============================================================================

DIGITAL_ASSETS = [
    {
        "id": "DOC-001",
        "document_name": "Mining Block Alpha - Detailed Survey Map 2024",
        "file_type": "GIS Shapefile + PDF",
        "file_size_mb": 125.4,
        "document_type": "Survey/GIS Map",
        "created_date": "2024-06-15",
        "last_updated": "2026-02-20",
        "version": "v2.3",
        "owner": "Siti Nurhaliza",
        "access_level": "Restricted",
        "stored_location": "Server /Survey_Maps/Alpha/",
        "backup_status": "Backed-up",
        "linked_concession": "CONC-001",
        "description": "Detailed topographical and geological survey of Mining Block Alpha with resource estimates",
    },
    {
        "id": "DOC-002",
        "document_name": "AutoCAD - Processing Facility Layout (Tin Smelter)",
        "file_type": "AutoCAD DWG",
        "file_size_mb": 45.2,
        "document_type": "Engineering Drawing",
        "created_date": "2016-08-10",
        "last_updated": "2025-11-05",
        "version": "v5.1",
        "owner": "Budi Santoso",
        "access_level": "Restricted",
        "stored_location": "Server /Engineering_Drawings/Smelter/",
        "backup_status": "Backed-up",
        "linked_facility": "FAC-001",
        "description": "Complete AutoCAD drawings of tin smelting facility with all equipment placements and utilities",
    },
    {
        "id": "DOC-003",
        "document_name": "Geospatial LIDAR Data - Surface Elevation Model",
        "file_type": "LAS Point Cloud + Orthomosaic",
        "file_size_mb": 2840.5,
        "document_type": "GIS/Remote Sensing Data",
        "created_date": "2025-01-10",
        "last_updated": "2026-01-10",
        "version": "v1.0",
        "owner": "Diana Putri",
        "access_level": "Confidential",
        "stored_location": "Data Center /GIS_Archive/LIDAR_2025/",
        "backup_status": "Triple Backed-up (Geo-redundant)",
        "coverage_concessions": ["CONC-001", "CONC-002"],
        "description": "High-resolution LIDAR data covering all mining concessions with 10cm vertical accuracy",
        "resolution_cm": 10,
        "point_density": 15,
    },
    {
        "id": "DOC-004",
        "document_name": "Environmental Impact Assessment Report 2023",
        "file_type": "PDF Report",
        "file_size_mb": 8.7,
        "document_type": "Compliance/Environmental Report",
        "created_date": "2023-01-15",
        "last_updated": "2026-01-15",
        "version": "Annual Update 2024",
        "owner": "Environmental Department",
        "access_level": "Restricted",
        "stored_location": "Server /Compliance_Docs/EA/",
        "backup_status": "Backed-up",
        "required_review_date": "2026-01-15",
        "regulatory_body": "AMDAL (Ministry of Environment)",
        "status": "Current",
    },
    {
        "id": "DOC-005",
        "document_name": "Drilling Log Database - Block Alpha (3D Multi-well)",
        "file_type": "Petrel Model + Well Logs",
        "file_size_mb": 342.1,
        "document_type": "Geological/Well Data",
        "created_date": "2020-06-20",
        "last_updated": "2026-03-18",
        "version": "Continuously Updated",
        "owner": "Geology Team",
        "access_level": "Internal",
        "stored_location": "Data Center /Petrel_Projects/",
        "backup_status": "Daily Backup",
        "wells_included": 47,
        "total_drilling_meters": 8950,
        "description": "Complete 3D geological model with integrated well logs from all exploration/production boreholes",
    },
    {
        "id": "DOC-006",
        "document_name": "Standard Operating Procedures (SOP) - Multi-document Bundle",
        "file_type": "PDF Bundle (25 documents)",
        "file_size_mb": 94.3,
        "document_type": "Operational Manual/SOP",
        "created_date": "2018-03-01",
        "last_updated": "2025-09-10",
        "version": "v3.2 (2025 Revision)",
        "owner": "Operations Manager",
        "access_level": "Internal",
        "stored_location": "Server /SOP_Library/",
        "backup_status": "Backed-up",
        "sop_count": 25,
        "coverage_areas": ["Safety", "Equipment Operation", "Maintenance", "Environmental", "Quality"],
    },
]

# ============================================================================
# 5. IT & DIGITAL INFRASTRUCTURE
# ============================================================================

IT_INFRASTRUCTURE = [
    {
        "id": "IT-001",
        "asset_name": "Database Server - PostgreSQL Production",
        "category": "IT Infrastructure",
        "subcategory": "Servers",
        "manufacturer": "Dell",
        "model": "PowerEdge R750",
        "serial_number": "IT-DELL-R750-001",
        "asset_status": "operational",
        "purchase_price": 45000.00,
        "current_value": 31500.00,
        "acquisition_date": "2021-06-15",
        "warranty_expiry": "2024-06-15",
        "location": "Data Center - Rack A2",
        "processor": "2x Intel Xeon Platinum 8380",
        "ram_gb": 384,
        "storage_tb": 12,
        "backup_status": "Daily backup to secondary site",
        "uptime_percent": "99.98%",
        "last_maintenance": "2026-03-10",
        "next_maintenance": "2026-04-10",
        "maintenance_interval_days": 30,
        "software_licenses": ["PostgreSQL Enterprise", "Backup Pro"],
        "linked_applications": ["TGd System", "Asset Registry", "CMMS"],
    },
    {
        "id": "IT-002",
        "asset_name": "GIS Server - ArcGIS Enterprise",
        "category": "IT Infrastructure",
        "subcategory": "Servers",
        "manufacturer": "HP",
        "model": "ProLiant DL380 Gen10",
        "serial_number": "IT-HP-DL380-002",
        "asset_status": "operational",
        "purchase_price": 38000.00,
        "current_value": 26600.00,
        "acquisition_date": "2021-09-20",
        "warranty_expiry": "2024-09-20",
        "location": "Data Center - Rack A3",
        "processor": "2x Intel Xeon Gold 6248",
        "ram_gb": 512,
        "storage_tb": 24,
        "backup_status": "Hourly backup to NAS",
        "uptime_percent": "99.95%",
        "last_maintenance": "2026-02-28",
        "next_maintenance": "2026-04-28",
        "software_licenses": ["ArcGIS Enterprise", "Esri Extensions"],
        "linked_users": 45,
        "concurrent_users": 12,
    },
    {
        "id": "IT-003",
        "asset_name": "Workstation - CAD/GIS Engineering Workstation",
        "category": "IT Infrastructure",
        "subcategory": "Workstations",
        "manufacturer": "HP",
        "model": "Z6 G5",
        "serial_number": "IT-HP-Z6-003",
        "asset_status": "operational",
        "purchase_price": 8500.00,
        "current_value": 5950.00,
        "acquisition_date": "2022-03-10",
        "warranty_expiry": "2025-03-10",
        "location": "Engineering Office - Floor 2",
        "processor": "Intel Xeon W-11955M",
        "ram_gb": 128,
        "storage_tb": 4,
        "gpu": "NVIDIA RTX A6000",
        "software_licenses": ["AutoCAD", "ArcGIS Pro", "QGIS"],
        "assigned_user": "Siti Nurhaliza",
        "last_maintenance": "2026-03-05",
        "next_maintenance": "2026-04-05",
    },
    {
        "id": "IT-004",
        "asset_name": "Network Switch - Core Router (Cisco ASR 9006)",
        "category": "IT Infrastructure",
        "subcategory": "Network Equipment",
        "manufacturer": "Cisco",
        "model": "ASR 9006",
        "serial_number": "IT-CISCO-ASR-004",
        "asset_status": "operational",
        "purchase_price": 18000.00,
        "current_value": 12600.00,
        "acquisition_date": "2020-12-01",
        "warranty_expiry": "2023-12-01",
        "location": "Network Room - Data Center",
        "ports": "20x 100GbE",
        "throughput_gbps": 2160,
        "uptime_percent": "99.99%",
        "redundancy": "Dual power, dual line cards",
        "last_maintenance": "2026-02-15",
        "software_version": "IOS XR 7.4.1",
    },
    {
        "id": "IT-005",
        "asset_name": "SaaS Software License Suite",
        "category": "IT Infrastructure",
        "subcategory": "Software Licenses",
        "vendor": "Microsoft",
        "product": "Office 365 Enterprise + Teams",
        "license_type": "Cloud Subscription",
        "seats_purchased": 150,
        "seats_used": 127,
        "seats_available": 23,
        "annual_cost": 24000.00,
        "subscription_start": "2024-01-01",
        "subscription_expiry": "2027-12-31",
        "days_until_expiry": 651,
        "coverage": ["Email", "SharePoint", "Teams", "OneDrive"],
        "license_status": "Active",
    },
    {
        "id": "IT-006",
        "asset_name": "IoT Sensor Devices - Equipment Monitoring",
        "category": "IT Infrastructure",
        "subcategory": "IoT Devices",
        "device_type": "Industrial IoT Sensors",
        "manufacturer": "Siemens",
        "model": "SITRANS LUT500",
        "total_devices": 24,
        "devices_active": 23,
        "devices_offline": 1,
        "asset_status": "mostly-operational",
        "purchase_price_per_unit": 12500.00,
        "total_purchase_price": 300000.00,
        "current_value": 210000.00,
        "acquisition_date": "2022-01-15",
        "warranty_expiry": "2025-01-15",
        "locations": ["Excavators", "Loaders", "Crushers", "Conveyor Systems"],
        "functions": ["Equipment health monitoring", "Vibration analysis", "Temperature", "Fuel consumption"],
        "data_transmission": "4G LTE + Satellite backup",
        "storage_location": "Cloud (AWS IoT)",
    },
]

# ============================================================================
# 6. INVENTORY & CONSUMABLES
# ============================================================================

CONSUMABLES_INVENTORY = [
    {
        "id": "CONS-001",
        "item_name": "Diesel Fuel - Premium Grade",
        "category": "Fuel",
        "unit": "Liters",
        "quantity_on_hand": 125000,
        "reorder_point": 50000,
        "reorder_quantity": 100000,
        "unit_cost": 1.25,
        "total_value": 156250.00,
        "supplier": "Shell Indonesia",
        "lead_time_days": 7,
        "last_received": "2026-03-10",
        "consumption_rate_daily": 2500,
        "status": "adequate",
        "quality_standard": "ASTM D2D",
        "storage_location": "Fuel Tank Farm (6x 20k-L tanks)",
    },
    {
        "id": "CONS-002",
        "item_name": "Lubricating Oil - Heavy Machinery Grade",
        "category": "Lubricants",
        "unit": "Liters",
        "quantity_on_hand": 8500,
        "reorder_point": 2000,
        "reorder_quantity": 5000,
        "unit_cost": 18.50,
        "total_value": 157250.00,
        "supplier": "Mobil Lubricants",
        "lead_time_days": 14,
        "last_received": "2026-02-25",
        "consumption_rate_weekly": 350,
        "status": "adequate",
        "viscosity": "SAE 40",
        "storage_location": "Warehouse - Oil Storage Area",
    },
    {
        "id": "CONS-003",
        "item_name": "Drill Bits - Tricone Type (Various Sizes)",
        "category": "Wear Items",
        "unit": "Pieces",
        "quantity_on_hand": 127,
        "reorder_point": 20,
        "reorder_quantity": 50,
        "unit_cost": 2850.00,
        "total_value": 362250.00,
        "supplier": "Atlas Tools International",
        "lead_time_days": 21,
        "last_received": "2026-01-20",
        "consumption_rate_monthly": 15,
        "status": "adequate",
        "specifications": ["6\", 7\", 8\", 9.5\", 12.25\" diameters"],
        "storage_location": "Warehouse - Consumables Rack C",
    },
    {
        "id": "CONS-004",
        "item_name": "Personal Protective Equipment (PPE) - Bulk Pack",
        "category": "Safety Equipment",
        "items": [
            {"type": "Hard Hat", "quantity": 450, "unit_cost": 15.00},
            {"type": "Safety Vest", "quantity": 480, "unit_cost": 22.50},
            {"type": "Safety Boots", "quantity": 420, "unit_cost": 65.00},
            {"type": "Gloves (pairs)", "quantity": 2000, "unit_cost": 3.50},
            {"type": "Respirators", "quantity": 280, "unit_cost": 45.00},
            {"type": "Eye Protection", "quantity": 600, "unit_cost": 8.00},
        ],
        "total_value": 42575.00,
        "unit": "Mixed",
        "supplier": "PT Safety Equipment Indonesia",
        "lead_time_days": 10,
        "last_received": "2026-02-15",
        "status": "adequate",
        "certification": "ISO 3864 compliant",
        "storage_location": "Warehouse - Safety Equipment",
    },
    {
        "id": "CONS-005",
        "item_name": "Conveyor Belt - Spare Rolls",
        "category": "Processing Equipment Spares",
        "unit": "Pieces",
        "quantity_on_hand": 18,
        "reorder_point": 5,
        "reorder_quantity": 10,
        "unit_cost": 8500.00,
        "total_value": 153000.00,
        "supplier": "ConveySys Global",
        "lead_time_days": 42,
        "last_received": "2025-12-01",
        "consumption_rate_quarterly": 3,
        "status": "adequate",
        "belt_width_mm": 1200,
        "specifications": "Rubber-faced steel pulley, 500kg capacity",
        "storage_location": "Warehouse - Conveyor Spares Section",
    },
    {
        "id": "CONS-006",
        "item_name": "Chemical Reagents - Flotation Chemicals",
        "category": "Processing Chemicals",
        "items": [
            {"chemical": "SIBX (Xanthate)", "quantity_kg": 5000, "unit_cost_per_kg": 12.50},
            {"chemical": "Frother", "quantity_kg": 3000, "unit_cost_per_kg": 18.00},
            {"chemical": "pH Modifier", "quantity_kg": 2500, "unit_cost_per_kg": 9.50},
            {"chemical": "Depressant", "quantity_kg": 1500, "unit_cost_per_kg": 15.00},
        ],
        "total_value": 138500.00,
        "supplier": "BASF Minerals",
        "lead_time_days": 30,
        "last_received": "2026-03-05",
        "status": "adequate",
        "consumption_rate_monthly_kg": 1200,
        "storage_location": "Chemical Storage Building (Temperature controlled)",
        "safety_certification": "MSDS certificates on file",
    },
]

# ============================================================================
# 7. HR ASSETS - CERTIFICATIONS & TRAINING RECORDS  
# ============================================================================

HR_ASSETS = [
    {
        "id": "HR-001",
        "employee_name": "Ahmad Wijaya",
        "employee_id": "EMP-2019-001",
        "position": "Heavy Equipment Operator",
        "department": "Operations",
        "certifications": [
            {
                "cert_name": "Heavy Equipment Operation License (Excavator)",
                "issuing_body": "Indonesian Mining Authority",
                "issue_date": "2019-05-10",
                "expiry_date": "2027-05-10",
                "location": "File: CERT-EXC-001",
                "status": "valid"
            },
            {
                "cert_name": "Safety & Health in Mining (OHSAS 18001)",
                "issuing_body": "SOL Indonesia",
                "issue_date": "2020-08-15",
                "expiry_date": "2026-08-15",
                "status": "expiring-soon"
            },
            {
                "cert_name": "Haul Truck Operation",
                "issuing_body": "Volvo Training Center",
                "issue_date": "2022-03-20",
                "expiry_date": "2025-03-20",
                "status": "expired"
            },
        ],
        "training_completed": [
            {"course": "Equipment Maintenance Basics", "completion_date": "2024-06-15", "provider": "In-house"},
            {"course": "Environmental Awareness in Mining", "completion_date": "2025-02-20", "provider": "AMDAL Training"},
        ],
        "competency_checklist": {
            "Excavator CAT390": "Certified",
            "Dozer D455": "Competent",
            "Haul Truck FMX": "Refresher needed",
            "Loader WA480": "Competent",
            "Safety Processes": "Certified"
        },
        "deployment_history": [
            {"equipment": "EQP-001", "from_date": "2025-01-01", "to_date": "present"},
            {"equipment": "VEH-001", "from_date": "2024-06-01", "to_date": "2024-12-31"},
        ],
    },
    {
        "id": "HR-002",
        "employee_name": "Siti Nurhaliza",
        "employee_id": "EMP-2020-015",
        "position": "GIS/Survey Specialist",
        "department": "Engineering",
        "certifications": [
            {
                "cert_name": "GIS Professional (GISP)",
                "issuing_body": "GISCI (US)",
                "issue_date": "2019-11-10",
                "expiry_date": "2027-11-10",
                "status": "valid"
            },
            {
                "cert_name": "Surveying & Mapping License",
                "issuing_body": "Indonesian Government",
                "issue_date": "2020-05-15",
                "expiry_date": "2028-05-15",
                "status": "valid"
            },
            {
                "cert_name": "Drone Pilot License (Unmanned Aerial Vehicle)",
                "issuing_body": "Kementerian Transportasi",
                "issue_date": "2021-08-20",
                "expiry_date": "2026-08-20",
                "status": "expiring-soon"
            },
        ],
        "software_proficiency": [
            "ArcGIS Pro - Expert",
            "AutoCAD - Advanced", 
            "QGIS - Advanced",
            "Petrel - Intermediate",
            "Drone mapping software - Expert"
        ],
    },
]

# ============================================================================
# 8. FINANCIAL ASSETS - DEPRECIATION & MAINTENANCE  
# ============================================================================

FINANCIAL_ASSETS = {
    "total_assets_owned": 32,
    "total_purchase_value": 42500000.00,
    "total_current_value": 28700000.00,
    "total_depreciation": 13800000.00,
    "depreciation_percentage": "32.4%",
    "annual_depreciation_rate": "7.0%",
    
    "depreciation_schedule": [
        {
            "asset_id": "EQP-001",
            "asset_name": "Excavator CAT 390F",
            "purchase_value": 1500000.00,
            "current_value": 1050000.00,
            "depreciated": 450000.00,
            "age_years": 5,
            "useful_life_years": 10,
            "residual_value": 300000.00,
            "depreciation_method": "Straight-line"
        },
        {
            "asset_id": "FAC-001",
            "asset_name": "Tin Smelter Plant",
            "purchase_value": 12000000.00,
            "current_value": 7200000.00,
            "depreciated": 4800000.00,
            "age_years": 10,
            "useful_life_years": 20,
            "residual_value": 2400000.00,
            "depreciation_method": "Straight-line"
        },
    ],
    
    "maintenance_cost_summary": {
        "ytd_total": 485300.00,
        "monthly_average": 40441.67,
        "by_category": {
            "Mining Equipment": 145000.00,
            "Processing Facilities": 98000.00,
            "Fleet Vehicles": 78500.00,
            "Infrastructure": 89800.00,
            "IT Systems": 12000.00,
            "Other": 61000.00,
        },
        "by_type": {
            "Preventive Maintenance": 285000.00,
            "Breakdown Repairs": 135200.00,
            "Overhauls": 45100.00,
            "Minor Repairs": 20000.00,
        }
    },
    
    "insurance_coverage": {
        "property_insurance": {
            "provider": "PT. Asuransi Bumiputera",
            "coverage_amount": 28700000.00,
            "annual_premium": 143500.00,
            "expiry_date": "2026-12-31",
            "deductible": 5000.00,
        },
        "equipment_breakdown": {
            "provider": "PT. AIG Indonesia",
            "coverage_amount": 15000000.00,
            "annual_premium": 87500.00,
            "expiry_date": "2026-06-30",
            "deductible": 10000.00,
        }
    }
}

# ============================================================================
# 9. ENVIRONMENTAL & SUSTAINABILITY ASSETS
# ============================================================================

ENVIRONMENTAL_ASSETS = [
    {
        "id": "ENV-001",
        "asset_name": "Dust Monitoring Sensor Network",
        "asset_type": "Environmental Monitoring Equipment",
        "manufacturer": "Thermo Fisher Scientific",
        "model": "FH 62 IR",
        "total_units": 12,
        "locations": [
            "Mining Block Alpha - Pit edge",
            "Processing Plant - Plant boundary",
            "Tailings Area - Northern zone",
            "Reclamation Area - Active sites",
            "Residential Area - Downwind",
            "Port Facility - Loading area"
        ],
        "status": "operational",
        "parameters_monitored": ["PM10", "PM2.5", "Total Dust"],
        "measurement_frequency": "Continuous (24/7)",
        "data_storage": "Cloud + Local logger",
        "alert_thresholds": {
            "PM10_ug_m3": 150,
            "PM2.5_ug_m3": 35,
        },
        "annual_exceedances_2025": 8,
        "purchase_date": "2022-01-15",
        "replacement_cycle_years": 5,
    },
    {
        "id": "ENV-002",
        "asset_name": "Water Quality Monitoring System",
        "asset_type": "Environmental Monitoring Equipment",
        "manufacturer": "YSI (Xylem)",
        "model": "ProDSS",
        "total_units": 6,
        "monitoring_points": [
            "Mining pit water",
            "Discharge point 1",
            "Discharge point 2",
            "Downstream river",
            "Offshore point 1",
            "Offshore point 2"
        ],
        "parameters": ["pH", "Dissolved Oxygen", "Turbidity", "Conductivity", "Temperature", "Metals"],
        "testing_frequency": "Daily + Weekly lab analysis",
        "compliance_standard": "Indonesian Environment Ministry Regulation",
        "purchase_date": "2020-06-01",
        "replacement_cycle_years": 4,
    },
    {
        "id": "ENV-003",
        "asset_name": "Tailings Storage Facility (TSF) - Geotechnical Monitoring",
        "asset_type": "Infrastructure + Monitoring",
        "installed_instruments": {
            "piezometers": 24,
            "settlement_plates": 18,
            "inclinometers": 12,
            "GPS_monuments": 8,
        },
        "total_storage_capacity_m3": 8500000,
        "current_fill_level_percentage": 76,
        "material_type": "Tailings slurry + coarse refuse",
        "operating_since": "2015-04-01",
        "dam_height_m": 42,
        "embankment_type": "Centerline construction",
        "stability_last_review": "2025-12-15",
        "next_review_date": "2026-12-15",
        "monitoring_frequency": "Daily + Monthly inspection",
        "seepage_rate_current": "Low (< 50 L/day)",
        "environmental_certification": "ISO 14001",
    },
    {
        "id": "ENV-004",
        "asset_name": "Biodiversity Offset Program - Land Restoration",
        "asset_type": "Environmental/Offset Program",
        "program_type": "Land Rehabilitation & Species Protection",
        "offset_area_hectares": 450,
        "locations": [
            "Reclaimed pit areas - 250 ha (replanting ongoing)",
            "Buffer zones - 150 ha (protected forest)",
            "Habitat corridor - 50 ha (wildlife passage)"
        ],
        "species_protected": ["Endangered birds", "Rare plants", "Aquatic life"],
        "trees_planted_to_date": 125000,
        "annual_planting_target": 50000,
        "status": "in-progress",
        "implementation_partner": "WWF Indonesia",
        "budget_allocated": 2500000.00,
        "monitoring_protocol": "Quarterly biodiversity surveys",
    },
    {
        "id": "ENV-005",
        "asset_name": "Carbon Emission Tracking System",
        "asset_type": "Environmental Management System",
        "scope": "Scope 1, 2, and 3 emissions",
        "baseline_year": 2020,
        "current_year_emissions_tonnes_co2": 18500,
        "baseline_year_emissions": 21300,
        "reduction_percentage": "13.2%",
        "emission_reduction_target": "Net zero by 2040",
        "short_term_target_2030": "30% reduction vs baseline",
        "monitored_sources": [
            "Vehicle fleet",
            "Power generation (on-site)",
            "Heavy equipment",
            "Smelting operations",
            "Supply chain",
        ],
        "renewable_energy_adoption": {
            "solar_panels_installed_kw": 500,
            "wind_turbines": 2,
            "annual_renewable_generation_kwh": 1250000,
            "renewable_percentage_of_total": "8.5%"
        },
        "certification_status": "ISO 14064-1 verified",
    },
]

# ============================================================================
# COMBINED ASSET REGISTRY
# ============================================================================

COMPLETE_ASSET_REGISTRY = {
    "1_physical_fixed_assets": {
        "mining_equipment": MINING_EQUIPMENT,
        "processing_facilities": MINING_EQUIPMENT[5:8],  # FAC-001, FAC-002, FAC-003
        "infrastructure": MINING_EQUIPMENT[8:12],  # INF-001 through INF-004
    },
    "2_fleet_vehicles": FLEET_VEHICLES,
    "3_land_concessions": MINING_CONCESSIONS,
    "4_digital_assets": DIGITAL_ASSETS,
    "5_it_infrastructure": IT_INFRASTRUCTURE,
    "6_consumables_inventory": CONSUMABLES_INVENTORY,
    "7_hr_assets": HR_ASSETS,
    "8_financial_assets": FINANCIAL_ASSETS,
    "9_environmental_assets": ENVIRONMENTAL_ASSETS,
    
    "statistics": {
        "total_assets": 9,
        "total_asset_categories": 9,
        "total_asset_value": 28700000.00,
        "total_physical_assets": 12,
        "total_fleet_units": 5,
        "total_digital_files": 6,
        "total_it_assets": 6,
        "total_consumable_items": 6,
        "total_employees_tracked": 2,
        "total_environmental_programs": 5,
    }
}

if __name__ == "__main__":
    import json
    print("Mining Asset Registry Data Loaded Successfully")
    print(f"Total Asset Categories: {COMPLETE_ASSET_REGISTRY['statistics']['total_asset_categories']}")
    print(f"Total Asset Value: ${COMPLETE_ASSET_REGISTRY['statistics']['total_asset_value']:,.2f}")
    print("\n✓ Data structure is ready for database seeding")
